# syntax=docker/dockerfile:1

FROM node

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install \
&& touch scores.csv

COPY . .

CMD [ "node", "score.js" ]
