#syntax=docker/dockerfile:1

FROM postgres
WORKDIR /app
COPY [ "package.json", "package-lock.json*", "score.js", "./" ]

RUN apt-get update && apt-get install -y npm wget
RUN npm install npm@latest -g && npm install n -g && n latest
RUN npm install

CMD [ "node", "score.js" ]
