name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  Build-App-macos:
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@main

    - name: Install Dependencies
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew update
        brew upgrade
        brew install docker docker-compose node npm
        brew services start docker

    - name: Start Project
      run: |
        docker-compose up -d

  Build-App-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@main

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt-get remove containerd.io
        sudo apt install docker.io docker-compose nodejs npm
        sudo systemctl enable docker --now

    - name: Run Project
      run: |
        sudo docker-compose up -d
        sleep 10

    - name: Stop Project
      run: |
        docker-compose down


  
        
